language: node_js
node_js:
  - "node"
services:
  - postgresql

addons:
  postgresql: '10.1'

env:
  global:
  - NODE_ENV=test    

before_script:
  - psql -c 'create database test_report_db;' -U postgres
  - psql test_report_db -U postgres < test/sql/create_test_user.sql
  - npm run fw:test-migrate

script:
    - npm run test

cache:
  directories:
    - "node_modules" 
