dist: trusty

language: node_js
node_js:
  - "lts/*"

services:
  - postgresql

addons:
  postgresql: '9.5'

env:
  global:
  - NODE_ENV=test    

install:
  - npm install

before_script:
  - psql -c "create user test with password 'test' createdb;" -U postgres
  - psql -c "ALTER USER test WITH superuser;" -U postgres
  - psql -c 'create database test_report_db with owner = test;' -U postgres
  - mkdir logs
  - cp test/example-flyway.conf test/flyway.conf
  
script:
    - npm run test
    - npm run lint

cache:
  directories:
    - "node_modules" 
