dist: trusty

language: node_js
node_js:
  - "node"

services:
  - postgresql

addons:
  postgresql: '9.5'

env:
  global:
  - NODE_ENV=test    

before_script:
  - psql -c "create user test with password 'test' createdb;" -U postgres
  - psql -c "ALTER USER test WITH superuser;" -U postgres
  - psql -c 'create database test_report_db with owner = test;' -U postgres
  - npm run fw:test-migrate
  
script:
    - npm run test

cache:
  directories:
    - "node_modules" 
